### ISSUE TITLE
DeepLar /home folder has only 7gb left

### ISSUE THREAD

**Issue by andrefdre** [lardemua/deep#9]
When trying to send dataset to deeplar it gave me the error saying there was no disk space left in /home folder. After I confirmed it by using command `df` giving me the following results.
![image](https://user-images.githubusercontent.com/58526188/216995062-3e60b60a-58bf-4556-94e1-b9fcb7c9ac2f.png)
As seen in image /home is at 98%.
What should be done, @DanielCoelho112 @vitoruapt @miguelriemoliveira?

**Comment by miguelriemoliveira** [comment]
Please put here a report of who / what is taking the space in the disk to help us decide how to proceed.

**Comment by andrefdre** [comment]
![image](https://user-images.githubusercontent.com/58526188/217008167-dbac1a8b-5542-412f-9e3d-5a6ed6dcf507.png)

**Comment by DanielCoelho112** [comment]
Hi @andrefdre,

I am using one folder as a backup for my experiments, but I found a way to be more memory-efficient. I will free some space in a couple of minutes.

**Comment by DanielCoelho112** [comment]
Done. You have now 70G available. Next week I'll probably free more space, but I think you're good now, right?

**Comment by andrefdre** [comment]
Yes for me it's more than enough. Thank you.
Do you think we should close the issue, or that this solution is just a short term fix?

**Comment by DanielCoelho112** [comment]
I think we can close this one. We can always reopen if necessary.

**Comment by miguelriemoliveira** [comment]
Great!

**Comment by Joel-Baptista** [comment]
We have several disks (sda, sdb, sdc, sdd, sde, sdf) totaling around 8 TB in storage that are not being used. Should we create a "data" folder where we mount every disk to store datasets?  
![image](https://user-images.githubusercontent.com/58263121/217341767-301ded45-a645-4e85-a036-3f060226db5c.png)

**Comment by miguelriemoliveira** [comment]
Hi @Joel-Baptista ,

Do you mean a virtual disk which puts toghether all available hardware disks?

I think thats dangerous solution, because if one hardware fails the entire virtual disk fails, right?

**Comment by Joel-Baptista** [comment]
> Hi @Joel-Baptista ,
> 
> Do you mean a virtual disk which puts toghether all available hardware disks?
> 
> I think thats dangerous solution, because if one hardware fails the entire virtual disk fails, right?

Hi @miguelriemoliveira,

It's not quite what I meant, but I see that I was not very clear before. Inside the "data" directory there would be one sub-directory for each hardware disk. The "data" folder was just for organization purposes.

**Comment by miguelriemoliveira** [comment]
Ah, I get it.

Usually, different dissk are not under a folder. 

Perhaps we could use the disks for different purposes, e.g., one for datasets, another for user documents ...

**Comment by Joel-Baptista** [comment]
It is also a good suggestion. Let's see what others think the folder organization should be

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira, @vitoruapt, @Joel-Baptista, @andrefdre.

the memory issues are now fixed.

I just mounted sda1 (1000GB) to /datasets and sdb1(1000GB) to /results. These disks weren't being used...

**Comment by miguelriemoliveira** [comment]
Great!
